name: Debug Azure File Share Mount

on: [push]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: 'Login to Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Container Instances'
        uses: azure/aci-deploy@v1
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: debug-container-${{ github.run_number }}
          image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.REPOSITORY_NAME }}:${{ github.run_number }}
          registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          name: debug-container
          location: 'northeurope'
          ports: '3000'
          azure-file-volume-account-name: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          azure-file-volume-account-key: ${{ secrets.AZURE_STORAGE_KEY }}
          azure-file-volume-share-name: container
          azure-file-volume-mount-path: /mnt/azurefiles

      - name: Debug Mount Path in Container
        run: |
          echo "Controleer mount path:"
          ls -l /mnt/azurefiles || echo "Het pad /mnt/azurefiles bestaat niet"
          echo "Test schrijven naar gemounte map"
          echo "Test Data" > /mnt/azurefiles/testfile.txt || echo "Kan niet schrijven naar /mnt/azurefiles"
          echo "Lees inhoud van testbestand:"
          cat /mnt/azurefiles/testfile.txt || echo "Kan bestand niet lezen"
