name: Fetch Data and Save to Azure File Share

on:
  push:
    branches:
      - main

jobs:
  fetch-and-save-data:
    runs-on: ubuntu-latest

    steps:
      # Stap 1: Checkout de repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Stap 2: Log in op Azure CLI met Service Principal (credentials)
      - name: Login to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Stap 3: Installeer de Azure Storage CLI-extensie (indien nodig)
      - name: Install Azure Storage CLI extension
        run: |
          az extension add --name storage-preview || echo "Extension already installed"

      # Stap 4: Haal de data van de website op (met curl, inclusief poortnummer)
      - name: Fetch data from website
        run: |
          curl -o fetched_data.txt "http://getting-started-21.northeurope.azurecontainer.io:3000/api/data"

      # Stap 5: Upload de opgehaalde data naar Azure File Share
      - name: Upload data to Azure File Share
        run: |
          az storage file upload \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --account-key ${{ secrets.AZURE_STORAGE_KEY }} \
            --share-name ${{ secrets.AZURE_FILE_SHARE_NAME }} \
            --source fetched_data.txt \
            --path fetched_data_${{ github.run_number }}.txt
